spring:
  profiles:
    active: local

  security:
    oauth2.client:
      authenticationScheme: header
      registration:
        42:
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          authorization-grant-type: authorization_code
          scope: public
      provider:
        42:
          authorization-uri: "https://api.intra.42.fr/oauth/authorize"
          token-uri: "https://api.intra.42.fr/oauth/token"
          user-info-uri: "https://api.intra.42.fr/v2/me"
          user-name-attribute: id

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: 42seoularcade@gmail.com
    password: ddejvefnkjscumxf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  # Message 설정
  messages:
    basename: 'messages/validation'
    encoding: UTF-8

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

jwt.secret: a2f6abd304bcd1d2ff9691bb0e7c1bab1010d0466c628d23b49550fb932300a43054a6030811f6118eb8129d9033cf5e2b63b762c5bd7bee246f63d34ee04fd3